title: 3Four Studios Ltd
tagline: Cross-platform mobile application development
author: "3FourStudios"
description: Cross-platform mobile application development
logo: /assets/img/logo.png
url: https://3fourstudios.com
twitter:
  card: summary_large_image
  username: 3FourStudios
social:
  name: 3FourStudios
  links:
    - https://twitter.com/3FourStudios/
    - https://www.linkedin.com/in/-simon-browne-/
    - https://github.com/Simon3FourStudios/
author:
  twitter: 3FourStudios

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
- username: -simon-browne-
  url: https://www.linkedin.com/in/-simon-browne-/
  icon: LinkedIn.svg
- username: "@3FourStudios"
  url: https://twitter.com/3FourStudios/
  icon: Twitter_Logo_Blue.svg
- username: Simon3FourStudios
  url: https://github.com/Simon3FourStudios/
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
